// Code generated by logcopter-gen; DO NOT EDIT.

package parsehelpers

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.geppetto.pkg.events.structuredsink.parsehelpers")
