// Code generated by logcopter-gen; DO NOT EDIT.

package openai_responses

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.geppetto.pkg.steps.ai.openai_responses")
