- type: local
  path: /home/manuel/workspaces/2025-10-30/implement-openai-responses-api/oak-git-db/docs/usage.md
  lastFetched: 2026-01-21T17:10:10.579196138-05:00
- type: local
  path: /home/manuel/workspaces/2025-10-30/implement-openai-responses-api/oak-git-db/docs/design.md
  lastFetched: 2026-01-21T17:10:12.189898174-05:00
- type: local
  path: /home/manuel/workspaces/2025-10-30/implement-openai-responses-api/oak-git-db/docs/implementation.md
  lastFetched: 2026-01-21T17:10:14.099420068-05:00
