// Code generated by cmd/gen-turns from turns_codegen.yaml. DO NOT EDIT.

export declare const GeppettoNamespaceKey: "geppetto";
export declare const BlockKindUser: "user";
export declare const BlockKindLLMText: "llm_text";
export declare const BlockKindToolCall: "tool_call";
export declare const BlockKindToolUse: "tool_use";
export declare const BlockKindSystem: "system";
export declare const BlockKindReasoning: "reasoning";
export declare const BlockKindOther: "other";

export type BlockKind =
    | "user"
    | "llm_text"
    | "tool_call"
    | "tool_use"
    | "system"
    | "reasoning"
    | "other"
    ;
export declare const ToolConfigValueKey: "tool_config";
export declare const StructuredOutputConfigValueKey: "structured_output_config";
export declare const InferenceConfigValueKey: "inference_config";
export declare const ClaudeInferenceConfigValueKey: "claude_inference_config";
export declare const OpenAIInferenceConfigValueKey: "openai_inference_config";
export declare const AgentModeAllowedToolsValueKey: "agent_mode_allowed_tools";
export declare const AgentModeValueKey: "agent_mode";
export declare const ResponsesServerToolsValueKey: "responses_server_tools";
export declare const TurnMetaProviderValueKey: "provider";
export declare const TurnMetaRuntimeValueKey: "runtime";
export declare const TurnMetaSessionIDValueKey: "session_id";
export declare const TurnMetaInferenceIDValueKey: "inference_id";
export declare const TurnMetaTraceIDValueKey: "trace_id";
export declare const TurnMetaUsageValueKey: "usage";
export declare const TurnMetaStopReasonValueKey: "stop_reason";
export declare const TurnMetaModelValueKey: "model";
export declare const BlockMetaClaudeOriginalContentValueKey: "claude_original_content";
export declare const BlockMetaToolCallsValueKey: "tool_calls";
export declare const BlockMetaMiddlewareValueKey: "middleware";
export declare const BlockMetaAgentModeTagValueKey: "agentmode_tag";
export declare const BlockMetaAgentModeValueKey: "agentmode";
