// Code generated by cmd/gen-meta. DO NOT EDIT.

package turns

import (
	"gopkg.in/yaml.v3"
	"strings"
)

// BlockKind represents the kind of a block within a Turn.
type BlockKind int

const (
	BlockKindUser      BlockKind = 0
	BlockKindLLMText   BlockKind = 1
	BlockKindToolCall  BlockKind = 2
	BlockKindToolUse   BlockKind = 3
	BlockKindSystem    BlockKind = 4
	BlockKindReasoning BlockKind = 5
	BlockKindOther     BlockKind = 6
)

// String returns a human-readable identifier for the BlockKind.
func (k BlockKind) String() string {
	switch k {
	case BlockKindUser:
		return "user"
	case BlockKindLLMText:
		return "llm_text"
	case BlockKindToolCall:
		return "tool_call"
	case BlockKindToolUse:
		return "tool_use"
	case BlockKindSystem:
		return "system"
	case BlockKindReasoning:
		return "reasoning"
	case BlockKindOther:
		return "other"
	default:
		return "other"
	}
}

// YAML serialization for BlockKind using stable string names
func (k BlockKind) MarshalYAML() (interface{}, error) {
	return k.String(), nil
}

func (k *BlockKind) UnmarshalYAML(value *yaml.Node) error {
	if value == nil {
		*k = BlockKindOther
		return nil
	}
	var s string
	if err := value.Decode(&s); err != nil {
		return err
	}
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "user":
		*k = BlockKindUser
	case "llm_text":
		*k = BlockKindLLMText
	case "tool_call":
		*k = BlockKindToolCall
	case "tool_use":
		*k = BlockKindToolUse
	case "system":
		*k = BlockKindSystem
	case "reasoning":
		*k = BlockKindReasoning
	case "other":
		*k = BlockKindOther
	case "":
		*k = BlockKindOther
	default:
		*k = BlockKindOther
	}
	return nil
}
