// Code generated by cmd/gen-turns. DO NOT EDIT.

package turns

// Canonical namespace for geppetto-owned turn data and metadata keys.
const GeppettoNamespaceKey = "geppetto"

// Canonical value keys (scoped to GeppettoNamespaceKey).
const (
	// Turn.Data
	ToolConfigValueKey             = "tool_config"
	StructuredOutputConfigValueKey = "structured_output_config"
	AgentModeAllowedToolsValueKey  = "agent_mode_allowed_tools"
	AgentModeValueKey              = "agent_mode"
	ResponsesServerToolsValueKey   = "responses_server_tools"

	// Turn.Metadata
	TurnMetaProviderValueKey    = "provider"
	TurnMetaRuntimeValueKey     = "runtime"
	TurnMetaSessionIDValueKey   = "session_id"
	TurnMetaInferenceIDValueKey = "inference_id"
	TurnMetaTraceIDValueKey     = "trace_id"
	TurnMetaUsageValueKey       = "usage"
	TurnMetaStopReasonValueKey  = "stop_reason"
	TurnMetaModelValueKey       = "model"

	// Block.Metadata
	BlockMetaClaudeOriginalContentValueKey = "claude_original_content"
	BlockMetaToolCallsValueKey             = "tool_calls"
	BlockMetaMiddlewareValueKey            = "middleware"
	BlockMetaAgentModeTagValueKey          = "agentmode_tag"
	BlockMetaAgentModeValueKey             = "agentmode"
)

// Typed keys for Turn.Data (geppetto-owned).
//
// Note: KeyToolConfig lives in `geppetto/pkg/inference/engine` to avoid the import cycle:
// turns -> engine (ToolConfig type) -> turns (Engine interface uses *turns.Turn)
var (
	KeyAgentModeAllowedTools = DataK[[]string](GeppettoNamespaceKey, AgentModeAllowedToolsValueKey, 1)
	KeyAgentMode             = DataK[string](GeppettoNamespaceKey, AgentModeValueKey, 1)
	KeyResponsesServerTools  = DataK[[]any](GeppettoNamespaceKey, ResponsesServerToolsValueKey, 1)
)

// Typed keys for Turn.Metadata (geppetto-owned).
var (
	KeyTurnMetaProvider    = TurnMetaK[string](GeppettoNamespaceKey, TurnMetaProviderValueKey, 1)
	KeyTurnMetaRuntime     = TurnMetaK[any](GeppettoNamespaceKey, TurnMetaRuntimeValueKey, 1)
	KeyTurnMetaSessionID   = TurnMetaK[string](GeppettoNamespaceKey, TurnMetaSessionIDValueKey, 1)
	KeyTurnMetaInferenceID = TurnMetaK[string](GeppettoNamespaceKey, TurnMetaInferenceIDValueKey, 1)
	KeyTurnMetaTraceID     = TurnMetaK[string](GeppettoNamespaceKey, TurnMetaTraceIDValueKey, 1)
	KeyTurnMetaUsage       = TurnMetaK[any](GeppettoNamespaceKey, TurnMetaUsageValueKey, 1)
	KeyTurnMetaStopReason  = TurnMetaK[string](GeppettoNamespaceKey, TurnMetaStopReasonValueKey, 1)
	KeyTurnMetaModel       = TurnMetaK[string](GeppettoNamespaceKey, TurnMetaModelValueKey, 1)
)

// Typed keys for Block.Metadata (geppetto-owned).
var (
	KeyBlockMetaClaudeOriginalContent = BlockMetaK[any](GeppettoNamespaceKey, BlockMetaClaudeOriginalContentValueKey, 1)
	KeyBlockMetaToolCalls             = BlockMetaK[any](GeppettoNamespaceKey, BlockMetaToolCallsValueKey, 1)
	KeyBlockMetaMiddleware            = BlockMetaK[string](GeppettoNamespaceKey, BlockMetaMiddlewareValueKey, 1)
	KeyBlockMetaAgentModeTag          = BlockMetaK[string](GeppettoNamespaceKey, BlockMetaAgentModeTagValueKey, 1)
	KeyBlockMetaAgentMode             = BlockMetaK[string](GeppettoNamespaceKey, BlockMetaAgentModeValueKey, 1)
)
