// Code generated by logcopter-gen; DO NOT EDIT.

package sections

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.geppetto.pkg.sections")
