slug: embeddings
name: Embeddings generation settings
description: Settings for generating embeddings from text
flags:
  - name: embeddings-engine
    type: string
    help: The model to use for embeddings generation
    default: "text-embedding-3-small"
  - name: embeddings-type
    type: choice
    choices:
      - "openai"
      - "ollama"
    help: The provider type to use for embeddings
    default: openai
  - name: embeddings-dimensions
    type: int
    help: The output dimension of the embeddings (384 for Ollama all-minilm, 1536 for OpenAI text-embedding-3-small)
    default: 1536 
  - name: embeddings-cache-type
    type: choice
    choices:
      - "none"
      - "memory"
      - "file"
    help: Type of caching to use for embeddings (none, memory, or disk)
    default: none
  - name: embeddings-cache-max-size
    type: int
    help: Maximum size of cache in bytes (for disk cache)
    default: 1073741824  # 1GB
  - name: embeddings-cache-max-entries
    type: int
    help: Maximum number of entries in cache (for memory cache)
    default: 1000
  - name: embeddings-cache-directory
    type: string
    help: Directory to store cache files (for disk cache)
    default: ""
