// Code generated by cmd/gen-js-api. DO NOT EDIT.

package geppetto

import "github.com/dop251/goja"

// installConsts installs the gp.consts namespace on the module exports.
func (m *moduleRuntime) installConsts(exports *goja.Object) {
	constsObj := m.vm.NewObject()

	// ToolChoice - How the model should choose tools
	{
		o := m.vm.NewObject()
		m.mustSet(o, "AUTO", "auto")
		m.mustSet(o, "NONE", "none")
		m.mustSet(o, "REQUIRED", "required")
		m.mustSet(constsObj, "ToolChoice", o)
	}

	// ToolErrorHandling - How to handle tool execution errors
	{
		o := m.vm.NewObject()
		m.mustSet(o, "CONTINUE", "continue")
		m.mustSet(o, "ABORT", "abort")
		m.mustSet(o, "RETRY", "retry")
		m.mustSet(constsObj, "ToolErrorHandling", o)
	}

	// BlockKind - The kind of a block within a Turn
	{
		o := m.vm.NewObject()
		m.mustSet(o, "USER", "user")
		m.mustSet(o, "LLM_TEXT", "llm_text")
		m.mustSet(o, "TOOL_CALL", "tool_call")
		m.mustSet(o, "TOOL_USE", "tool_use")
		m.mustSet(o, "SYSTEM", "system")
		m.mustSet(o, "REASONING", "reasoning")
		m.mustSet(o, "OTHER", "other")
		m.mustSet(constsObj, "BlockKind", o)
	}

	// HookAction - Actions returned from tool hook callbacks
	{
		o := m.vm.NewObject()
		m.mustSet(o, "ABORT", "abort")
		m.mustSet(o, "RETRY", "retry")
		m.mustSet(o, "CONTINUE", "continue")
		m.mustSet(constsObj, "HookAction", o)
	}

	// MetadataKeys - Standard turn metadata key names
	{
		o := m.vm.NewObject()
		m.mustSet(o, "PROVIDER", "provider")
		m.mustSet(o, "RUNTIME", "runtime")
		m.mustSet(o, "SESSION_ID", "session_id")
		m.mustSet(o, "INFERENCE_ID", "inference_id")
		m.mustSet(o, "TRACE_ID", "trace_id")
		m.mustSet(o, "USAGE", "usage")
		m.mustSet(o, "STOP_REASON", "stop_reason")
		m.mustSet(o, "MODEL", "model")
		m.mustSet(constsObj, "MetadataKeys", o)
	}

	// EventType - Streaming event types for RunHandle.on()
	{
		o := m.vm.NewObject()
		m.mustSet(o, "START", "start")
		m.mustSet(o, "PARTIAL", "partial")
		m.mustSet(o, "FINAL", "final")
		m.mustSet(o, "TOOL_CALL", "tool-call")
		m.mustSet(o, "TOOL_RESULT", "tool-result")
		m.mustSet(o, "ERROR", "error")
		m.mustSet(constsObj, "EventType", o)
	}

	m.mustSet(exports, "consts", constsObj)
}
