// Code generated by cmd/gen-meta. DO NOT EDIT.

package geppetto

import "github.com/dop251/goja"

// installConsts installs the gp.consts namespace on the module exports.
func (m *moduleRuntime) installConsts(exports *goja.Object) {
	constsObj := m.vm.NewObject()

	// BlockKind - The kind of a block within a Turn
	{
		o := m.vm.NewObject()
		m.mustSet(o, "USER", "user")
		m.mustSet(o, "LLM_TEXT", "llm_text")
		m.mustSet(o, "TOOL_CALL", "tool_call")
		m.mustSet(o, "TOOL_USE", "tool_use")
		m.mustSet(o, "SYSTEM", "system")
		m.mustSet(o, "REASONING", "reasoning")
		m.mustSet(o, "OTHER", "other")
		m.mustSet(constsObj, "BlockKind", o)
	}

	// TurnDataKeys - Canonical Turn.Data value keys
	{
		o := m.vm.NewObject()
		m.mustSet(o, "TOOL_CONFIG", "tool_config")
		m.mustSet(o, "STRUCTURED_OUTPUT_CONFIG", "structured_output_config")
		m.mustSet(o, "INFERENCE_CONFIG", "inference_config")
		m.mustSet(o, "CLAUDE_INFERENCE_CONFIG", "claude_inference_config")
		m.mustSet(o, "OPENAI_INFERENCE_CONFIG", "openai_inference_config")
		m.mustSet(o, "AGENT_MODE_ALLOWED_TOOLS", "agent_mode_allowed_tools")
		m.mustSet(o, "AGENT_MODE", "agent_mode")
		m.mustSet(o, "RESPONSES_SERVER_TOOLS", "responses_server_tools")
		m.mustSet(constsObj, "TurnDataKeys", o)
	}

	// TurnMetadataKeys - Canonical Turn.Metadata value keys
	{
		o := m.vm.NewObject()
		m.mustSet(o, "PROVIDER", "provider")
		m.mustSet(o, "RUNTIME", "runtime")
		m.mustSet(o, "SESSION_ID", "session_id")
		m.mustSet(o, "INFERENCE_ID", "inference_id")
		m.mustSet(o, "TRACE_ID", "trace_id")
		m.mustSet(o, "USAGE", "usage")
		m.mustSet(o, "STOP_REASON", "stop_reason")
		m.mustSet(o, "MODEL", "model")
		m.mustSet(constsObj, "TurnMetadataKeys", o)
	}

	// BlockMetadataKeys - Canonical Block.Metadata value keys
	{
		o := m.vm.NewObject()
		m.mustSet(o, "CLAUDE_ORIGINAL_CONTENT", "claude_original_content")
		m.mustSet(o, "TOOL_CALLS", "tool_calls")
		m.mustSet(o, "MIDDLEWARE", "middleware")
		m.mustSet(o, "AGENTMODE_TAG", "agentmode_tag")
		m.mustSet(o, "AGENTMODE", "agentmode")
		m.mustSet(constsObj, "BlockMetadataKeys", o)
	}

	// RunMetadataKeys - Canonical Run.Metadata value keys
	{
		o := m.vm.NewObject()
		m.mustSet(o, "TRACE_ID", "trace_id")
		m.mustSet(constsObj, "RunMetadataKeys", o)
	}

	// PayloadKeys - Canonical Block.Payload key names
	{
		o := m.vm.NewObject()
		m.mustSet(o, "TEXT", "text")
		m.mustSet(o, "ID", "id")
		m.mustSet(o, "NAME", "name")
		m.mustSet(o, "ARGS", "args")
		m.mustSet(o, "RESULT", "result")
		m.mustSet(o, "ERROR", "error")
		m.mustSet(o, "IMAGES", "images")
		m.mustSet(o, "ENCRYPTED_CONTENT", "encrypted_content")
		m.mustSet(o, "ITEM_ID", "item_id")
		m.mustSet(constsObj, "PayloadKeys", o)
	}

	// ToolChoice - How the model should choose tools
	{
		o := m.vm.NewObject()
		m.mustSet(o, "AUTO", "auto")
		m.mustSet(o, "NONE", "none")
		m.mustSet(o, "REQUIRED", "required")
		m.mustSet(constsObj, "ToolChoice", o)
	}

	// ToolErrorHandling - How to handle tool execution errors
	{
		o := m.vm.NewObject()
		m.mustSet(o, "CONTINUE", "continue")
		m.mustSet(o, "ABORT", "abort")
		m.mustSet(o, "RETRY", "retry")
		m.mustSet(constsObj, "ToolErrorHandling", o)
	}

	// HookAction - Actions returned from tool hook callbacks
	{
		o := m.vm.NewObject()
		m.mustSet(o, "ABORT", "abort")
		m.mustSet(o, "RETRY", "retry")
		m.mustSet(o, "CONTINUE", "continue")
		m.mustSet(constsObj, "HookAction", o)
	}

	// EventType - Streaming event types for RunHandle.on()
	{
		o := m.vm.NewObject()
		m.mustSet(o, "START", "start")
		m.mustSet(o, "PARTIAL", "partial")
		m.mustSet(o, "FINAL", "final")
		m.mustSet(o, "TOOL_CALL", "tool-call")
		m.mustSet(o, "TOOL_RESULT", "tool-result")
		m.mustSet(o, "ERROR", "error")
		m.mustSet(constsObj, "EventType", o)
	}

	m.mustSet(exports, "consts", constsObj)
}
