// Code generated by logcopter-gen; DO NOT EDIT.

package geppetto

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.geppetto.pkg.js.modules.geppetto")
