// Code generated by logcopter-gen; DO NOT EDIT.

package enginebuilder

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.geppetto.pkg.inference.toolloop.enginebuilder")
