#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../../../../../../.." && pwd)"
cd "$ROOT"
OUT="geppetto/ttmp/2026/06/01/GP-GOJA-API-2026-06-01--review-and-redesign-geppetto-go-go-goja-api-and-javascript-bindings/sources/01-code-evidence.md"
{
  echo "---"
  echo "Title: Code evidence for Geppetto go-go-goja API review"
  echo "Ticket: GP-GOJA-API-2026-06-01"
  echo "Status: active"
  echo "Topics: [geppetto, js-bindings, goja, inference]"
  echo "DocType: reference"
  echo "Intent: transient"
  echo "Owners: []"
  echo "RelatedFiles: []"
  echo "ExternalSources: []"
  echo "Summary: Line-numbered source evidence generated by scripts/01-collect-evidence.sh."
  echo "LastUpdated: $(date -Iseconds)"
  echo "WhatFor: Evidence snapshot for the API review design doc."
  echo "WhenToUse: When checking file-backed claims in the design doc."
  echo "---"
  echo
  echo "# Code evidence for Geppetto go-go-goja API review"
  echo
  echo "Generated: $(date -Iseconds)"
  echo
  for f in \
    geppetto/pkg/js/modules/geppetto/module.go \
    geppetto/pkg/js/modules/geppetto/api_types.go \
    geppetto/pkg/js/modules/geppetto/codec.go \
    geppetto/pkg/js/modules/geppetto/api_turns.go \
    geppetto/pkg/js/modules/geppetto/api_engines.go \
    geppetto/pkg/js/modules/geppetto/api_sessions.go \
    geppetto/pkg/js/modules/geppetto/api_builder_options.go \
    geppetto/pkg/js/modules/geppetto/api_tools_registry.go \
    geppetto/pkg/js/modules/geppetto/api_runner.go \
    geppetto/pkg/js/modules/geppetto/api_events.go \
    geppetto/pkg/js/modules/geppetto/provider/provider.go \
    geppetto/pkg/js/runtime/runtime.go \
    geppetto/pkg/js/embeddings-js.go \
    geppetto/pkg/doc/types/geppetto.d.ts \
    go-go-goja/pkg/xgoja/providerapi/module.go \
    go-go-goja/pkg/xgoja/app/factory.go \
    go-go-goja/pkg/xgoja/app/host.go \
    go-go-goja/pkg/xgoja/doc/01-runtime-overview.md \
    pinocchio/pkg/doc/topics/13-js-api-reference.md \
    pinocchio/pkg/inference/runtime/engine.go \
    pinocchio/pkg/inference/runtime/composer.go \
    pinocchio/pkg/chatapp/runtime_inference.go \
    pinocchio/pkg/chatapp/runtime_sink.go
  do
    if [[ -f "$f" ]]; then
      echo "## $f"
      echo '```text'
      nl -ba "$f" | sed -n '1,260p'
      echo '```'
      echo
    fi
  done
} > "$OUT"
echo "$OUT"
