// Code generated by cmd/gen-meta from geppetto_codegen.yaml. DO NOT EDIT.

/** Hard-cut wrapper-first Geppetto JavaScript API. */
declare module "geppetto" {
    export const version: string;

    export interface Block {
        id?: string;
        kind: string;
        role?: string;
        payload?: Record<string, any>;
        metadata?: Record<string, any>;
    }

    export interface Turn {
        id?: string;
        blocks: Block[];
        metadata?: Record<string, any>;
        data?: Record<string, any>;
    }

    export const consts: {
        BlockKind: Record<string, string>;
        TurnDataKeys: Record<string, string>;
        TurnMetadataKeys: Record<string, string>;
        BlockMetadataKeys: Record<string, string>;
        RunMetadataKeys: Record<string, string>;
        PayloadKeys: Record<string, string>;
        ToolChoice: Record<string, string>;
        ToolErrorHandling: Record<string, string>;
        HookAction: Record<string, string>;
        EventType: Record<string, string>;
    };

    export interface ModelCost {
        input: number;
        output: number;
        cacheRead: number;
        cacheWrite: number;
    }

    export interface ModelInfo {
        id?: string;
        name?: string;
        reasoning?: boolean;
        input?: string[];
        contextWindow?: number;
        qualityHighWatermark?: number;
        maxOutputTokens?: number;
        cost?: ModelCost;
        metadata?: Record<string, any>;
    }

    export interface Engine {
        name: string;
        metadata?: Record<string, any>;
        modelInfo?: ModelInfo;
    }

    export interface RegistrySummary {
        slug: string;
        display_name?: string;
        default_profile_slug?: string;
        profile_count: number;
    }

    export interface ProfileRef {
        registry_slug?: string;
        profile_slug: string;
    }

    export interface ProfileMetadata {
        source?: string;
        version?: number;
        created_at_ms?: number;
        updated_at_ms?: number;
        created_by?: string;
        updated_by?: string;
        tags?: string[];
    }

    export interface Profile {
        slug: string;
        display_name?: string;
        description?: string;
        stack?: ProfileRef[];
        inference_settings?: Record<string, any>;
        metadata?: ProfileMetadata;
        extensions?: Record<string, any>;
    }

    export type ProfileRegistrySources = string | string[];
    export type ResolveProfileInput = string | { registry?: string; registrySlug?: string; profile?: string; profileSlug?: string };

    export interface InferenceSettings {
        toJSON(): Record<string, any>;
        clone(): InferenceSettings;
        debug(): Record<string, any>;
    }

    export interface InferenceRegistry {
        sources: string[];
        listRegistries(): RegistrySummary[];
        listProfiles(registrySlug?: string): Profile[];
        resolve(input?: ResolveProfileInput): InferenceSettings;
        close(): void;
    }

    export const inferenceProfiles: {
        load(source: ProfileRegistrySources): InferenceRegistry;
        resolve(input?: ResolveProfileInput): InferenceSettings;
        default(): InferenceRegistry;
    };

    export interface EngineBuilder {
        inference(settings: InferenceSettings): EngineBuilder;
        build(): Engine;
    }

    export function engine(): EngineBuilder;

    export interface MessageBuilder {
        text(text: string): MessageBuilder;
        imageURL(url: string, options?: Record<string, any>): MessageBuilder;
        imageFile(path: string): MessageBuilder;
        imageBytes(content: string, mediaType?: string): MessageBuilder;
    }

    export interface TurnWrapper {
        toJSON(): Turn;
        clone(): TurnWrapper;
    }

    export interface TurnBuilder {
        system(text: string): TurnBuilder;
        user(text: string | ((message: MessageBuilder) => MessageBuilder)): TurnBuilder;
        assistant(text: string): TurnBuilder;
        metadata(key: string, value: any): TurnBuilder;
        build(): TurnWrapper;
    }

    /**
     * Create a new TurnBuilder. When base is supplied, it must be a Go-owned
     * TurnWrapper; the builder clones its blocks/metadata and clears the copied
     * turn id so the result is a continuation turn rather than the same
     * persisted turn. Use TurnWrapper.clone() for an exact identity-preserving
     * copy.
     */
    export function turn(base?: TurnWrapper): TurnBuilder;

    export interface TurnStoreQuery {
        convId?: string;
        conversationId?: string;
        sessionId?: string;
        sessionID?: string;
        phase?: string;
        sinceMs?: number;
        limit?: number;
    }

    export interface TurnStoreSnapshot {
        convId: string;
        sessionId: string;
        turnId: string;
        phase: string;
        runtimeKey: string;
        inferenceId: string;
        createdAtMs: number;
        turn: TurnWrapper | null;
        toJSON(): Record<string, any>;
    }

    export interface TurnStore {
        name(): string;
        list(query?: TurnStoreQuery): TurnStoreSnapshot[];
        loadLatest(query?: TurnStoreQuery): TurnStoreSnapshot | null;
        close(): void;
    }

    export const turnStores: {
        default(): TurnStore;
        get(name: string): TurnStore;
    };

    export interface RunOptions {
        timeoutMs?: number;
        tags?: Record<string, any>;
    }

    export interface RunResult {
        inputTurn(): TurnWrapper;
        effectiveTurn(): TurnWrapper;
        outputTurn(): TurnWrapper;
        text(): string;
        usage(): any;
        stopReason(): string | null;
        events(): any[];
        toJSON(): Record<string, any>;
    }

    export interface EventCorrelation {
        session_id?: string;
        run_id?: string;
        turn_id?: string;
        provider_call_id?: string;
        segment_id?: string;
        tool_call_id?: string;
    }

    export interface EventUsage {
        input_tokens?: number;
        output_tokens?: number;
        cached_tokens?: number;
        cache_creation_input_tokens?: number;
        cache_read_input_tokens?: number;
    }

    export interface GeppettoEventBase {
        type: string;
        timestampMs: number;
        sessionId?: string;
        inferenceId?: string;
        turnId?: string;
        correlation?: EventCorrelation;
        metaExtra?: Record<string, any>;
        rawPayload?: string;
    }

    export type GeppettoEvent =
        | (GeppettoEventBase & { type: "run-started"; prompt?: string })
        | (GeppettoEventBase & { type: "run-finished"; status?: string })
        | (GeppettoEventBase & { type: "run-stopped"; reason?: string })
        | (GeppettoEventBase & { type: "run-failed"; error?: string; message?: string })
        | (GeppettoEventBase & { type: "provider-call-started" })
        | (GeppettoEventBase & { type: "provider-call-metadata-updated"; stopReason?: string; stopSequence?: string; usage?: EventUsage })
        | (GeppettoEventBase & { type: "provider-call-finished"; stopReason?: string; finishClass?: string; usage?: EventUsage; durationMs?: number; hasToolCalls?: boolean })
        | (GeppettoEventBase & { type: "text-segment-started"; role?: string })
        | (GeppettoEventBase & { type: "text-delta"; delta: string; text: string; sequence?: number })
        | (GeppettoEventBase & { type: "text-segment-finished"; text: string; finishReason?: string })
        | (GeppettoEventBase & { type: "reasoning-segment-started"; source?: string })
        | (GeppettoEventBase & { type: "reasoning-delta"; delta: string; text: string; sequence?: number; source?: string })
        | (GeppettoEventBase & { type: "reasoning-segment-finished"; text?: string; finishReason?: string; source?: string })
        | (GeppettoEventBase & { type: "tool-call-started"; toolCall: { id: string; name?: string } })
        | (GeppettoEventBase & { type: "tool-call-arguments-delta"; toolCall: { id: string; delta: string; arguments: string; sequence?: number } })
        | (GeppettoEventBase & { type: "tool-call-requested"; toolCall: { id: string; name: string; input: string } })
        | (GeppettoEventBase & { type: "tool-execution-started"; toolCall: { id: string; name?: string; input?: string } })
        | (GeppettoEventBase & { type: "tool-result-ready"; toolResult: { id: string; name?: string; result: string; status?: string } })
        | (GeppettoEventBase & { type: "tool-call-finished"; toolCall: { id: string; name?: string; status?: string } })
        | (GeppettoEventBase & { type: "error"; error?: string; message?: string })
        | (GeppettoEventBase & { type: "interrupt"; text: string })
        | (GeppettoEventBase & { type: "log"; level: string; message: string; fields?: Record<string, any> })
        | (GeppettoEventBase & { type: "info"; message: string; data?: Record<string, any> })
        | (GeppettoEventBase & { type: "agent-mode-switch"; message: string; data?: Record<string, any> })
        | (GeppettoEventBase & { type: string; [key: string]: any });

    export interface EventEmitterLike {
        on(name: "event", listener: (event: GeppettoEvent) => void): this;
        on(name: string | symbol, listener: (...args: any[]) => void): this;
        once(name: "event", listener: (event: GeppettoEvent) => void): this;
        once(name: string | symbol, listener: (...args: any[]) => void): this;
        off(name: string | symbol, listener: (...args: any[]) => void): this;
        emit(name: string | symbol, ...args: any[]): boolean;
    }

    export interface AgentAsyncHandle {
        promise: Promise<RunResult>;
        cancel(): void;
        close(): void;
    }

    export interface Agent {
        name: string;
        run(turn: TurnWrapper, options?: RunOptions): RunResult;
        runAsync(turn: TurnWrapper, options?: RunOptions): AgentAsyncHandle;
    }

    export interface AgentBuilder {
        name(name: string): AgentBuilder;
        inference(settings: InferenceSettings): AgentBuilder;
        engine(engine: Engine): AgentBuilder;
        middleware(middleware: any): AgentBuilder;
        goMiddleware(name: string, options?: Record<string, any>): AgentBuilder;
        tool(registry: ToolRegistryBuilder): AgentBuilder;
        goTool(name: string): AgentBuilder;
        toolLoop(options?: Record<string, any>): AgentBuilder;
        events(sink: any | EventEmitterLike): AgentBuilder;
        persistTo(store: TurnStore | null): AgentBuilder;
        persistDefault(enabled?: boolean): AgentBuilder;
        runDefaults(options?: RunOptions): AgentBuilder;
        build(): Agent;
    }

    export function agent(): AgentBuilder;

    export interface Schema {
        toJSON(): Record<string, any>;
        clone(): Schema;
    }

    export interface SchemaBuilder {
        description(text: string): SchemaBuilder;
        property(name: string, schema: Schema | SchemaBuilder): SchemaBuilder;
        items(schema: Schema | SchemaBuilder): SchemaBuilder;
        required(...names: string[]): SchemaBuilder;
        build(): Schema;
        toJSON(): Record<string, any>;
    }

    export const schema: {
        string(): SchemaBuilder;
        integer(): SchemaBuilder;
        number(): SchemaBuilder;
        boolean(): SchemaBuilder;
        array(): SchemaBuilder;
        object(): SchemaBuilder;
        enum(...values: any[]): SchemaBuilder;
    };

    export interface ToolSpec {
        name: string;
        description: string;
        toJSON(): Record<string, any>;
    }

    export interface ToolBuilder {
        description(text: string): ToolBuilder;
        input(schema: Schema | SchemaBuilder | Record<string, any>): ToolBuilder;
        handler(fn: (input: any, context: any) => any): ToolBuilder;
        build(): ToolSpec;
    }

    export function tool(name: string): ToolBuilder;

    export interface ToolRegistryBuilder {
        add(tool: ToolSpec): ToolRegistryBuilder;
        addGo(...names: string[]): ToolRegistryBuilder;
        list(): Array<{ name: string; description?: string; version?: string; tags?: string[] }>;
        call(name: string, input?: Record<string, any>): any;
    }

    export function toolRegistry(): ToolRegistryBuilder;

}
